version: "2"
services:
  giftless-test:
    extends:
      file: "docker-compose.yml"
      service: "giftless"
    environment:
      - GIFTLESS_DEBUG=1
    volumes:
      - "./nginx-test.conf:/etc/nginx/conf.d/default.conf"
      - "./lfs-test-storage:/lfs-storage"
      - "./test-db:/var/lib/git-lfs-authenticate"
  nginx:
    image: nginx
    volumes:
      - "./nginx-test.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "6428:80"
  ssh-server:
    build: ./ssh-server
    volumes:
      - "./id_ssh-user.pub:/home/user/id_ssh-user.pub"
      - "../git-lfs-authenticate.py:/usr/local/bin/git-lfs-authenticate"
      - "./ssh-server/git-lfs-authenticate.ini:/etc/git-lfs-authenticate.ini"
      - "./test-db:/var/lib/git-lfs-authenticate"
    ports:
      - "6422:22"
