---
- name: create /opt/docker-compose
  file:
    path: /opt/docker-compose
    state: directory

- name: create /data directories
  file:
    path: "{{ item }}"
    owner: lfs
    group: lfs
    state: directory
  loop:
    - /data/lfs
    - /data/lfs/storage

# These directories and files are owned by root because the user the lfs
# service runs as should not have permission to configure itself to be a
# different service
- name: create /opt/docker-compose dirs
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  loop:
    - /opt/docker-compose
    - /opt/docker-compose/lfs

- name: copy
  copy:
    dest: /opt/docker-compose/lfs/{{ item }}
    src: ../../../../docker-compose/{{ item }}
    owner: root
    group: root
    mode: '0644'
  loop:
    - giftless.yaml
    - token_database.py
    - docker-compose.yml

- name: create service file
  template:
    dest: /etc/systemd/system/docker-compose-lfs.service
    src: docker-compose-lfs.service.j2

# If this was a normal service where restart and so on actually worked,
# we’d set up handlers to restart the service if the config file changed.

- name: validate service file
  command: systemd-analyze verify /etc/systemd/system/docker-compose-lfs.service

- name: enable docker-compose-lfs
  systemd:
    name: docker-compose-lfs.service
    state: started
    enabled: yes
